### ISSUE TITLE
Errors processing: cannot configure nginx-full

### ISSUE THREAD

**Issue by universe241981** [GuLinux/AstroPhoto-Plus#118] opened 2019-02-24 10:15 UTC
Installation stucked at nginx-full configuation

**Comment by GuLinux** [comment] 2019-02-24 10:50
I assume this is a duplicate of https://github.com/GuLinux/AstroPhoto-Plus/issues/117 ?
If not feel free to reopen the ticket, but please specify on what device (or better, Linux distribution) you're installing the package, and attach some logs.

**Closed by GuLinux** 2019-02-24 10:50 UTC
